export const CONSULTEASE_PROFILE_SEARCH = "CONSULTEASE_PROFILE_SEARCH"
export const CONSULTEASE_PROFILE_SEARCH_RESULTS =
  "CONSULTEASE_PROFILE_SEARCH_RESULTS"
export const CONSULTEASE_PROFILE_SEARCH_RESULTS_RESET =
  "CONSULTEASE_PROFILE_SEARCH_RESULTS_RESET"
